version: '2'
services:
  webapi:
    build: .
    depends_on:
      - fwbdata
    restart: always
    ports:
      - 9090:8080
    volumes:
      - ./fwbdata/git:/git
  fwbdata:
    build: fwbdata
    volumes:
      - ./fwbdata/git:/git
    

