version: '2'
services:
  webapi:
    build: .
    restart: always
    ports:
      - 9090:8080
    volumes:
      - ./gitclone/git:/git
      - ./import-files:/import-files
    environment:
      - GIT_DIR=/git/fwb-daten
      - OUTPUT_DIR=/import-files
    env_file:
      - .env
  gitclone:
    build: gitclone
    volumes:
      - ./gitclone/git:/git
    env_file:
      - .env
    

