version: '2'
services:
  webapi:
    build: .
    restart: always
    ports:
      - 9090:8080
    volumes:
      - ./gitclone/git:/git
  gitclone:
    build: gitclone
    volumes:
      - ./gitclone/git:/git
    

